<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GUSH.Utils.DateTimeToolKit" Version="1.2.2" />
    <PackageReference Include="System.Text.Json" Version="8.0.6" />
  </ItemGroup>

</Project>
